// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using BrainMoodML.Model;

namespace BrainMoodML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = "TODO";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Emotion with predicted Emotion from sample data...\n\n");
            Console.WriteLine($"alphaHigh: {sampleData.AlphaHigh}");
            Console.WriteLine($"alphaLow: {sampleData.AlphaLow}");
            Console.WriteLine($"betaHigh: {sampleData.BetaHigh}");
            Console.WriteLine($"betaLow: {sampleData.BetaLow}");
            Console.WriteLine($"delta: {sampleData.Delta}");
            Console.WriteLine($"gammaHigh: {sampleData.GammaHigh}");
            Console.WriteLine($"gammaLow: {sampleData.GammaLow}");
            Console.WriteLine($"theta: {sampleData.Theta}");
            Console.WriteLine($"attention: {sampleData.Attention}");
            Console.WriteLine($"meditation: {sampleData.Meditation}");
            Console.WriteLine($"\n\nActual Emotion: {sampleData.Emotion} \nPredicted Emotion value {predictionResult.Prediction} \nPredicted Emotion scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ';',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
