// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BrainMoodML.Model
{
    public class ModelInput
    {
        [ColumnName("alphaHigh"), LoadColumn(0)]
        public float AlphaHigh { get; set; }


        [ColumnName("alphaLow"), LoadColumn(1)]
        public float AlphaLow { get; set; }


        [ColumnName("betaHigh"), LoadColumn(2)]
        public float BetaHigh { get; set; }


        [ColumnName("betaLow"), LoadColumn(3)]
        public float BetaLow { get; set; }


        [ColumnName("delta"), LoadColumn(4)]
        public float Delta { get; set; }


        [ColumnName("gammaHigh"), LoadColumn(5)]
        public float GammaHigh { get; set; }


        [ColumnName("gammaLow"), LoadColumn(6)]
        public float GammaLow { get; set; }


        [ColumnName("theta"), LoadColumn(7)]
        public float Theta { get; set; }


        [ColumnName("attention"), LoadColumn(8)]
        public float Attention { get; set; }


        [ColumnName("meditation"), LoadColumn(9)]
        public float Meditation { get; set; }


        [ColumnName("emotion"), LoadColumn(10)]
        public bool Emotion { get; set; }


    }
}
